server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  shardingshpere:
    datasource:
      names:
        master, slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.1:3306/reggie?characterEncoding=utf-8
        username: root
        password: root
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.2:3306/reggie?characterEncoding=utf-8
        username: root
        password: root
      masterslave:
        # 读写分离配置
        load-balance-algorithm-type: round_robin  #轮询
        # 最终的数据源名称
        name: dataSource
        #主库数据源名称
        master-data-source-name: master
        # 从库数据源名称列表，用逗号分隔
        slave-data-source-name: slave
      props:
        sql:
          show: true  #开启SQL显示，默认false
    main:
      allow-bean-definition-overriding: true  #允许bean定义覆盖配置项
  devtools:
    restart:
      enabled: false
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0
  cache:
    redis:
      time-to-live: 1800000
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: C:\DevResources\imgs\